#!/usr/bin/env php
<?php

// BYPASS LDAP CONSTANT ERROR
if (!defined('LDAP_OPT_PROTOCOL_VERSION')) {
    define('LDAP_OPT_PROTOCOL_VERSION', 3);
}

use Illuminate\Foundation\Application;
use Symfony\Component\Console\Input\ArgvInput;

define('LARAVEL_START', microtime(true));

// Register the Composer autoloader...
require __DIR__.'/vendor/autoload.php';

// Bootstrap Laravel and handle the command...
/** @var Application $app */
$app = require_once __DIR__.'/bootstrap/app.php';

$status = $app->handleCommand(new ArgvInput);

exit($status);
